# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
   apt:
    packages:
     - libxml2-dev # for XML
     - libudunits2-dev

branches:
  only:
  - master
  - develop

